<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
            [
                'code' => 'CUST00001',
                'name' => 'PT. Maju Jaya',
                'email' => 'info@majujaya.com',
                'phone' => '021-5551234',
                'address' => 'Jl. Sudirman No. 123, Jakarta Pusat, DKI Jakarta',
                'city' => 'Jakarta',
                'postal_code' => '10110',
                'type' => 'business',
                'tax_id' => '01.234.567.8-901.000',
                'credit_limit' => 50000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Customer premium dengan pembayaran tepat waktu. Payment terms: Net 30, Discount: 5%',
            ],
            [
                'code' => 'CUST00002',
                'name' => 'CV. Berkah Abadi',
                'email' => 'purchasing@berkah.co.id',
                'phone' => '022-6667890',
                'address' => 'Jl. Asia Afrika No. 45, Bandung, Jawa Barat',
                'city' => 'Bandung',
                'postal_code' => '40111',
                'type' => 'business',
                'tax_id' => '02.345.678.9-012.000',
                'credit_limit' => 30000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Customer reguler. Payment terms: Net 15, Discount: 3%',
            ],
            [
                'code' => 'CUST00003',
                'name' => 'Toko Sumber Rezeki',
                'email' => 'sumberrezeki@gmail.com',
                'phone' => '031-8881234',
                'address' => 'Jl. Tunjungan No. 78, Surabaya, Jawa Timur',
                'city' => 'Surabaya',
                'postal_code' => '60275',
                'type' => 'business',
                'tax_id' => '03.456.789.0-123.000',
                'credit_limit' => 20000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Pembayaran cash on delivery. Payment terms: COD, Discount: 2%',
            ],
            [
                'code' => 'CUST00004',
                'name' => 'UD. Sejahtera',
                'email' => 'udsejahtera@yahoo.com',
                'phone' => '024-3334567',
                'address' => 'Jl. Pemuda No. 90, Semarang, Jawa Tengah',
                'city' => 'Semarang',
                'postal_code' => '50132',
                'type' => 'business',
                'tax_id' => '04.567.890.1-234.000',
                'credit_limit' => 15000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Customer baru. Payment terms: Net 7',
            ],
            [
                'code' => 'CUST00005',
                'name' => 'PT. Global Niaga',
                'email' => 'procurement@globalniaga.com',
                'phone' => '061-4445678',
                'address' => 'Jl. Gatot Subroto No. 56, Medan, Sumatera Utara',
                'city' => 'Medan',
                'postal_code' => '20235',
                'type' => 'business',
                'tax_id' => '05.678.901.2-345.000',
                'credit_limit' => 75000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Customer korporat dengan volume besar. Payment terms: Net 45, Discount: 7.5%',
            ],
            [
                'code' => 'CUST00006',
                'name' => 'Minimarket Bahagia',
                'email' => 'bahagia.mart@gmail.com',
                'phone' => '0274-555789',
                'address' => 'Jl. Malioboro No. 123, Yogyakarta, DI Yogyakarta',
                'city' => 'Yogyakarta',
                'postal_code' => '55271',
                'type' => 'business',
                'tax_id' => '06.789.012.3-456.000',
                'credit_limit' => 10000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Jaringan minimarket lokal. Payment terms: Net 14, Discount: 2.5%',
            ],
            [
                'code' => 'CUST00007',
                'name' => 'Hotel Mewah Sentosa',
                'email' => 'purchasing@hotelmewah.com',
                'phone' => '0361-777888',
                'address' => 'Jl. Sunset Road No. 88, Kuta, Bali',
                'city' => 'Denpasar',
                'postal_code' => '80361',
                'type' => 'business',
                'tax_id' => '07.890.123.4-567.000',
                'credit_limit' => 40000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Hotel bintang 5, order rutin bulanan. Payment terms: Net 30, Discount: 5%',
            ],
            [
                'code' => 'CUST00008',
                'name' => 'Restoran Nusantara',
                'email' => 'nusantara.resto@outlook.com',
                'phone' => '021-8889999',
                'address' => 'Jl. Kemang Raya No. 45, Jakarta Selatan, DKI Jakarta',
                'city' => 'Jakarta',
                'postal_code' => '12730',
                'type' => 'business',
                'tax_id' => '08.901.234.5-678.000',
                'credit_limit' => 25000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Restoran chain dengan 5 cabang. Payment terms: Net 21, Discount: 3%',
            ],
            [
                'code' => 'CUST00009',
                'name' => 'Koperasi Karyawan Sejahtera',
                'email' => 'koperasi@sejahtera.co.id',
                'phone' => '021-4441111',
                'address' => 'Jl. HR Rasuna Said Kav. B-12, Jakarta, DKI Jakarta',
                'city' => 'Jakarta',
                'postal_code' => '12940',
                'type' => 'business',
                'tax_id' => '09.012.345.6-789.000',
                'credit_limit' => 35000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Koperasi dengan 1000+ anggota. Payment terms: Net 30, Discount: 4%',
            ],
            [
                'code' => 'CUST00010',
                'name' => 'Supermarket Hemat',
                'email' => 'admin@superhemat.com',
                'phone' => '0251-333444',
                'address' => 'Jl. Pajajaran No. 100, Bogor, Jawa Barat',
                'city' => 'Bogor',
                'postal_code' => '16143',
                'type' => 'business',
                'tax_id' => '10.123.456.7-890.000',
                'credit_limit' => 60000000,
                'outstanding_balance' => 15000000,
                'is_active' => false,
                'notes' => 'Temporarily inactive - pending payment. Payment terms: Net 60, Discount: 8%',
            ],
            [
                'code' => 'CUST00011',
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@gmail.com',
                'phone' => '0812-3456-7890',
                'address' => 'Jl. Melati No. 15, Tangerang',
                'city' => 'Tangerang',
                'postal_code' => '15117',
                'type' => 'individual',
                'tax_id' => null,
                'credit_limit' => 5000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Customer perorangan, pembayaran tunai',
            ],
            [
                'code' => 'CUST00012',
                'name' => 'Ibu Siti Nurhaliza',
                'email' => 'siti.nurhaliza@yahoo.com',
                'phone' => '0821-9876-5432',
                'address' => 'Perumahan Griya Indah Blok C-12, Bekasi',
                'city' => 'Bekasi',
                'postal_code' => '17121',
                'type' => 'individual',
                'tax_id' => null,
                'credit_limit' => 3000000,
                'outstanding_balance' => 0,
                'is_active' => true,
                'notes' => 'Customer tetap, order mingguan',
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }

        $this->command->info('Customers seeded successfully!');
    }
}