<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\RawMaterial;
use App\Models\Supplier;

class RawMaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get supplier IDs for relationships
        $suppliers = Supplier::pluck('id', 'code')->toArray();

        $rawMaterials = [
            [
                'code' => 'RM001',
                'name' => 'Gula Cair',
                'description' => 'Gula cair untuk produksi jamu kemasan',
                'category' => 'Pemanis',
                'unit' => 'Liter',
                'minimum_stock' => 100,
                'current_stock' => 250,
                'maximum_stock' => 500,
                'reorder_point' => 150,
                'reorder_quantity' => 200,
                'last_purchase_price' => 15000,
                'average_price' => 14500,
                'supplier_id' => $suppliers['SUP00001'] ?? null,
                'storage_location' => 'Gudang A - Rak 1',
                'lead_time_days' => 3,
                'is_active' => true,
                'notes' => 'Gula cair berkualitas tinggi untuk produksi jamu',
            ],
            [
                'code' => 'RM002',
                'name' => 'Temulawak',
                'description' => 'Temulawak segar untuk ekstrak jamu',
                'category' => 'Rempah',
                'unit' => 'Kg',
                'minimum_stock' => 50,
                'current_stock' => 120,
                'maximum_stock' => 200,
                'reorder_point' => 75,
                'reorder_quantity' => 100,
                'last_purchase_price' => 25000,
                'average_price' => 24000,
                'supplier_id' => $suppliers['SUP00002'] ?? null,
                'storage_location' => 'Gudang B - Rak 3',
                'lead_time_days' => 2,
                'is_active' => true,
                'notes' => 'Temulawak pilihan dari petani lokal',
            ],
            [
                'code' => 'RM003',
                'name' => 'Jahe Merah',
                'description' => 'Jahe merah segar untuk produksi jamu',
                'category' => 'Rempah',
                'unit' => 'Kg',
                'minimum_stock' => 30,
                'current_stock' => 75,
                'maximum_stock' => 150,
                'reorder_point' => 50,
                'reorder_quantity' => 75,
                'last_purchase_price' => 35000,
                'average_price' => 33000,
                'supplier_id' => $suppliers['SUP00002'] ?? null,
                'storage_location' => 'Gudang B - Rak 4',
                'lead_time_days' => 2,
                'is_active' => true,
                'notes' => 'Jahe merah berkualitas premium',
            ],
            [
                'code' => 'RM004',
                'name' => 'Botol Plastik 250ml',
                'description' => 'Botol plastik PET untuk kemasan jamu',
                'category' => 'Kemasan',
                'unit' => 'Pcs',
                'minimum_stock' => 1000,
                'current_stock' => 2500,
                'maximum_stock' => 5000,
                'reorder_point' => 1500,
                'reorder_quantity' => 2000,
                'last_purchase_price' => 1500,
                'average_price' => 1450,
                'supplier_id' => $suppliers['SUP00003'] ?? null,
                'storage_location' => 'Gudang C - Rak 1',
                'lead_time_days' => 1,
                'is_active' => true,
                'notes' => 'Botol PET food grade',
            ],
            [
                'code' => 'RM005',
                'name' => 'Label Stiker',
                'description' => 'Label stiker untuk produk jamu',
                'category' => 'Kemasan',
                'unit' => 'Lembar',
                'minimum_stock' => 500,
                'current_stock' => 1200,
                'maximum_stock' => 2500,
                'reorder_point' => 750,
                'reorder_quantity' => 1000,
                'last_purchase_price' => 500,
                'average_price' => 480,
                'supplier_id' => $suppliers['SUP00003'] ?? null,
                'storage_location' => 'Gudang C - Rak 2',
                'lead_time_days' => 1,
                'is_active' => true,
                'notes' => 'Label waterproof dengan desain custom',
            ],
            [
                'code' => 'RM006',
                'name' => 'Kunyit',
                'description' => 'Kunyit segar untuk ekstrak jamu',
                'category' => 'Rempah',
                'unit' => 'Kg',
                'minimum_stock' => 25,
                'current_stock' => 60,
                'maximum_stock' => 120,
                'reorder_point' => 40,
                'reorder_quantity' => 60,
                'last_purchase_price' => 18000,
                'average_price' => 17500,
                'supplier_id' => $suppliers['SUP00002'] ?? null,
                'storage_location' => 'Gudang B - Rak 5',
                'lead_time_days' => 2,
                'is_active' => true,
                'notes' => 'Kunyit organik berkualitas',
            ],
            [
                'code' => 'RM007',
                'name' => 'Tepung Tapioka',
                'description' => 'Tepung tapioka untuk pengental',
                'category' => 'Bahan Tambahan',
                'unit' => 'Kg',
                'minimum_stock' => 20,
                'current_stock' => 45,
                'maximum_stock' => 100,
                'reorder_point' => 30,
                'reorder_quantity' => 50,
                'last_purchase_price' => 12000,
                'average_price' => 11500,
                'supplier_id' => $suppliers['SUP00004'] ?? null,
                'storage_location' => 'Gudang A - Rak 3',
                'lead_time_days' => 5,
                'is_active' => true,
                'notes' => 'Tepung tapioka halus',
            ],
            [
                'code' => 'RM008',
                'name' => 'Minyak Kelapa',
                'description' => 'Minyak kelapa murni untuk campuran',
                'category' => 'Minyak',
                'unit' => 'Liter',
                'minimum_stock' => 15,
                'current_stock' => 5,
                'maximum_stock' => 50,
                'reorder_point' => 20,
                'reorder_quantity' => 30,
                'last_purchase_price' => 45000,
                'average_price' => 43000,
                'supplier_id' => $suppliers['SUP00005'] ?? null,
                'storage_location' => 'Gudang A - Rak 5',
                'lead_time_days' => 3,
                'is_active' => true,
                'notes' => 'Minyak kelapa VCO',
            ],
            [
                'code' => 'RM009',
                'name' => 'Kardus Kemasan',
                'description' => 'Kardus untuk packaging produk',
                'category' => 'Kemasan',
                'unit' => 'Pcs',
                'minimum_stock' => 100,
                'current_stock' => 180,
                'maximum_stock' => 400,
                'reorder_point' => 150,
                'reorder_quantity' => 200,
                'last_purchase_price' => 3500,
                'average_price' => 3400,
                'supplier_id' => $suppliers['SUP00003'] ?? null,
                'storage_location' => 'Gudang C - Rak 5',
                'lead_time_days' => 1,
                'is_active' => true,
                'notes' => 'Kardus corrugated 3 lapis',
            ],
            [
                'code' => 'RM010',
                'name' => 'Asam Jawa',
                'description' => 'Asam jawa untuk perasa alami',
                'category' => 'Rempah',
                'unit' => 'Kg',
                'minimum_stock' => 10,
                'current_stock' => 8,
                'maximum_stock' => 30,
                'reorder_point' => 15,
                'reorder_quantity' => 20,
                'last_purchase_price' => 22000,
                'average_price' => 21000,
                'supplier_id' => $suppliers['SUP00002'] ?? null,
                'storage_location' => 'Gudang B - Rak 6',
                'lead_time_days' => 2,
                'is_active' => true,
                'notes' => 'Asam jawa matang pilihan',
            ],
        ];

        foreach ($rawMaterials as $material) {
            RawMaterial::create($material);
        }

        echo "Raw materials seeded successfully!\n";
    }
}